# Generated by Django 4.0.6 on 2022-08-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_modulo', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=40)),
                ('url', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sesion', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(default=None, max_length=50)),
                ('url', models.SlugField(unique=True)),
                ('content_1', models.TextField(blank=True, null=True)),
                ('content_2', models.TextField(blank=True, null=True)),
                ('content_3', models.TextField(blank=True, null=True)),
                ('content_4', models.TextField(blank=True, null=True)),
                ('content_5', models.TextField(blank=True, null=True)),
                ('modulo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_sesion', to='home.modulo')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
    ]
