# Generated by Django 4.0.6 on 2022-08-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_modulo_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.JSONField(null=True)),
                ('sesion', models.JSONField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_access', to='home.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('url', models.SlugField(unique_for_date='created')),
                ('puntos', models.PositiveSmallIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_progreso', to='home.person')),
            ],
            options={
                'verbose_name': 'Progreso del Jugador',
                'verbose_name_plural': 'Progreso de los Jugadores',
            },
        ),
    ]
