# Generated by Django 4.0.6 on 2022-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_useraccess_progresoperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='sesion',
        ),
        migrations.AddField(
            model_name='modulo',
            name='checkpoint',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresoperson',
            name='next',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='checkpoint',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='next',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='posicion',
            field=models.SlugField(blank=True, null=True, unique_for_date='created'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
