# Generated by Django 4.0.6 on 2022-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_useraccess_modulo_remove_useraccess_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresoperson',
            name='next',
            field=models.SlugField(blank=True, null=True, unique_for_date='created'),
        ),
    ]
