# Generated by Django 4.0.6 on 2022-08-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_modulo', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=40)),
                ('url', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('checkpoint', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sesion', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(default=None, max_length=50)),
                ('url', models.SlugField(unique=True)),
                ('content_1', models.TextField(blank=True, null=True)),
                ('content_2', models.TextField(blank=True, null=True)),
                ('content_3', models.TextField(blank=True, null=True)),
                ('content_4', models.TextField(blank=True, null=True)),
                ('content_5', models.TextField(blank=True, null=True)),
                ('checkpoint', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_sesion', to='game.modulo')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('url', models.SlugField(unique_for_date='created')),
                ('next', models.SlugField(blank=True, null=True, unique_for_date='created')),
                ('puntos', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso del Jugador',
                'verbose_name_plural': 'Progreso de los Jugadores',
            },
        ),
    ]
