# Generated by Django 4.0.6 on 2022-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='introduccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
