# Generated by Django 4.0.6 on 2022-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_progresoplayer_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dir/frontpage/'),
        ),
    ]
