# Generated by Django 4.0.6 on 2022-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_modulo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='image_portada',
            field=models.ImageField(blank=True, null=True, upload_to='dir/portada/'),
        ),
    ]
